---
updates:
  - directory: /
    groups:
      github-actions:
        patterns:
          # Covers official GitHub actions
          - "actions/*"
          # Covers official Docker actions
          - "docker/*"
          # Cover the action we use to update the Docker Hub description
          - "peter-evans/dockerhub-description"
    package-ecosystem: github-actions
    schedule:
      interval: weekly

version: 2
