---
updates:
  - directory: /
    groups:
      github-actions:
        patterns:
          # Covers official GitHub actions
          - "actions/*"
          # Covers official Docker actions
          - "docker/*"
    package-ecosystem: github-actions
    schedule:
      interval: weekly

version: 2
